name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-branch: [rails6, rails7, rails7-shakapacker]

    continue-on-error: ${{ matrix.test-branch == 'rails7-shakapacker' }} # TODO: jamesmartin/inline_svg#156

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout test app
      uses: actions/checkout@v4
      with:
        repository: tagliala/inline_svg_test_app
        ref: ${{ matrix.test-branch }}
        path: test_app
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.2' # Ref: ruby/ruby#11006
        bundler-cache: true
    - name: Build local gem
      run: |
        bundle exec rake build
    - name: Use the local gem in the test App
      id: uselocalgem
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "gem 'inline_svg'"
        replace: "gem 'inline_svg', path: '${{github.workspace}}'"
    - name: Check local gem in use
      run: |
        test "${{ steps.uselocalgem.outputs.modifiedFiles }}" != "0"
        grep "inline_svg" $GITHUB_WORKSPACE/test_app/Gemfile
    - name: Bundle
      run: |
        cd $GITHUB_WORKSPACE/test_app
        bundle install --jobs 4 --retry 3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
      if: matrix.test-branch == 'rails7-shakapacker'
    - name: Generate Shakapacker config
      run: |
        cd $GITHUB_WORKSPACE/test_app
        yarn install --check-files
        bundle exec rake shakapacker:compile
      if: matrix.test-branch == 'rails7-shakapacker'
    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/test_app
        bundle exec rake test
